apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-training
  namespace: sports-prediction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-training
  template:
    metadata:
      labels:
        app: model-training
    spec:
      containers:
        - name: model-training
          image: ghcr.io/pierrebond/sports-model-training:latest
          envFrom:
            - configMapRef:
                name: sports-config
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: sports-api-key
                  key: API_KEY
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          restartPolicy: OnFailure
