from __future__ import annotations

from contextlib import asynccontextmanager
from datetime import datetime, timezone

from fastapi import FastAPI
from fastapi.responses import HTMLResponse, JSONResponse
from pydantic import BaseModel

from sports_common.logging import setup_logging, get_logger

setup_logging("reporting-service")
logger = get_logger(__name__)


class ReportRequest(BaseModel):
    match_id: str
    home_team: str
    away_team: str
    include_shap: bool = True
    include_betting: bool = True


class ReportResponse(BaseModel):
    report_id: str
    match_id: str
    generated_at: datetime
    html_content: str | None = None
    markdown_content: str | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("reporting_service_starting")
    yield
    logger.info("reporting_service_shutting_down")


app = FastAPI(
    title="Reporting Service",
    description="Match research report generation",
    version="0.1.0",
    lifespan=lifespan,
)


@app.get("/health")
async def health_check():
    return {"status": "healthy", "service": "reporting"}


@app.post("/reports/generate", response_model=ReportResponse)
async def generate_report(request: ReportRequest):
    logger.info("generating_report", match_id=request.match_id)

    report_id = f"report_{request.match_id}_{datetime.now().timestamp()}"

    markdown = f"""# Match Research Report

## {request.home_team} vs {request.away_team}

**Generated:** {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}

### Tactical Preview

- Expected formations: 4-3-3 vs 4-4-2
- Press intensity: High / Medium
- Build-up style comparison: Possession-based vs Counter-attack

### Market Dynamics

- Opening line: {request.home_team} -0.5
- Current line: {request.home_team} -0.25
- Sharp money indicator: Home
- CLV: +2.3%

### Probabilistic Forecasts

| Outcome | Probability |
|---------|-------------|
| {request.home_team} Win | 45% |
| Draw | 25% |
| {request.away_team} Win | 30% |

### Strategic Recommendations

1. **{request.home_team} -0.25** @ 1.91 (Medium confidence)
2. **{request.home_team} to score first** @ 1.75 (Low confidence)

---

*Generated by Sports Prediction System*
"""

    return ReportResponse(
        report_id=report_id,
        match_id=request.match_id,
        generated_at=datetime.now(timezone.utc),
        markdown_content=markdown,
    )


@app.get("/reports/{report_id}")
async def get_report(report_id: str):
    return {
        "report_id": report_id,
        "status": "ready",
        "markdown": "# Sample Report Content",
    }
