from __future__ import annotations

import uuid
from contextlib import asynccontextmanager
from datetime import datetime, timezone

import structlog
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import HTMLResponse, JSONResponse
from pydantic import BaseModel

from sports_common.logging import setup_logging, get_logger
from sports_common.security import setup_security

setup_logging("reporting-service")
logger = get_logger(__name__)


class ReportRequest(BaseModel):
    """Request body for report generation."""

    match_id: str
    home_team: str
    away_team: str
    include_shap: bool = True
    include_betting: bool = True


class ReportResponse(BaseModel):
    """Generated match research report."""

    report_id: str
    match_id: str
    generated_at: datetime
    html_content: str | None = None
    markdown_content: str | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initialize and tear down the reporting service."""
    logger.info("reporting_service_starting")
    yield
    logger.info("reporting_service_shutting_down")


app = FastAPI(
    title="Reporting Service",
    description="Match research report generation",
    version="0.1.0",
    lifespan=lifespan,
)

setup_security(app)


@app.middleware("http")
async def correlation_id_middleware(request: Request, call_next):
    """Inject correlation_id into structlog context for every request (RULE-22)."""
    correlation_id = request.headers.get("X-Correlation-ID", str(uuid.uuid4()))
    structlog.contextvars.clear_contextvars()
    structlog.contextvars.bind_contextvars(correlation_id=correlation_id)
    response = await call_next(request)
    response.headers["X-Correlation-ID"] = correlation_id
    return response


@app.exception_handler(HTTPException)
async def structured_http_exception_handler(request: Request, exc: HTTPException) -> JSONResponse:
    """Return structured error JSON per RULE-19."""
    return JSONResponse(
        status_code=exc.status_code,
        content={
            "error": exc.detail if isinstance(exc.detail, str) else str(exc.detail),
            "detail": exc.detail if isinstance(exc.detail, str) else str(exc.detail),
            "code": exc.status_code,
        },
    )


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    """Catch-all for unhandled errors, returning structured JSON."""
    logger.error("unhandled_exception", error=str(exc), exc_info=True)
    return JSONResponse(
        status_code=500,
        content={
            "error": "Internal server error",
            "detail": str(exc),
            "code": 500,
        },
    )


@app.get("/health")
async def health_check() -> dict[str, str]:
    """Check reporting service health status."""
    return {"status": "healthy", "service": "reporting"}


@app.post("/reports/generate", response_model=ReportResponse)
async def generate_report(request: ReportRequest) -> ReportResponse:
    """Generate a match research report."""
    logger.info("generating_report", match_id=request.match_id)

    report_id = f"report_{request.match_id}_{datetime.now().timestamp()}"

    markdown = f"""# Match Research Report

## {request.home_team} vs {request.away_team}

**Generated:** {datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")}

### Tactical Preview

- Expected formations: 4-3-3 vs 4-4-2
- Press intensity: High / Medium
- Build-up style comparison: Possession-based vs Counter-attack

### Market Dynamics

- Opening line: {request.home_team} -0.5
- Current line: {request.home_team} -0.25
- Sharp money indicator: Home
- CLV: +2.3%

### Probabilistic Forecasts

| Outcome | Probability |
|---------|-------------|
| {request.home_team} Win | 45% |
| Draw | 25% |
| {request.away_team} Win | 30% |

### Strategic Recommendations

1. **{request.home_team} -0.25** @ 1.91 (Medium confidence)
2. **{request.home_team} to score first** @ 1.75 (Low confidence)

---

*Generated by Sports Prediction System*
"""

    return ReportResponse(
        report_id=report_id,
        match_id=request.match_id,
        generated_at=datetime.now(timezone.utc),
        markdown_content=markdown,
    )


@app.get("/reports/{report_id}")
async def get_report(report_id: str) -> dict[str, str]:
    """Get a previously generated report by ID."""
    return {
        "report_id": report_id,
        "status": "ready",
        "markdown": "# Sample Report Content",
    }
