from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass
class MatchResearchSnapshot:
    """Assembled research snapshot for a single match (Section L.2).

    Aggregates tactical preview, market dynamics, probabilistic forecasts,
    SHAP explainability, and strategic recommendations.
    """

    match_id: str
    home_team: str
    away_team: str
    generated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    # Probabilistic forecasts
    home_win_prob: float = 0.0
    draw_prob: float = 0.0
    away_win_prob: float = 0.0
    predicted_home_score: float | None = None
    predicted_away_score: float | None = None

    # SHAP explanation
    shap_positive_drivers: list[dict[str, Any]] = field(default_factory=list)
    shap_negative_drivers: list[dict[str, Any]] = field(default_factory=list)

    # Market data
    opening_odds_home: float | None = None
    closing_odds_home: float | None = None
    line_movement: float | None = None
    sharp_money_indicator: str | None = None
    clv: float | None = None

    # Biometric summary
    home_team_avg_acwr: float | None = None
    away_team_avg_acwr: float | None = None
    home_injury_risk_score: float | None = None
    away_injury_risk_score: float | None = None

    # Value bets
    value_bets: list[dict[str, Any]] = field(default_factory=list)


def build_markdown_report(snapshot: MatchResearchSnapshot) -> str:
    """Render a MatchResearchSnapshot as a Markdown report.

    Args:
        snapshot: The assembled match research data.

    Returns:
        Markdown string of the full match report.
    """
    lines = [
        f"# Match Research Report",
        "",
        f"## {snapshot.home_team} vs {snapshot.away_team}",
        "",
        f"**Generated:** {snapshot.generated_at.strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "### Probabilistic Forecasts",
        "",
        "| Outcome | Probability |",
        "|---------|-------------|",
        f"| {snapshot.home_team} Win | {snapshot.home_win_prob:.1%} |",
        f"| Draw | {snapshot.draw_prob:.1%} |",
        f"| {snapshot.away_team} Win | {snapshot.away_win_prob:.1%} |",
        "",
    ]

    if snapshot.predicted_home_score is not None and snapshot.predicted_away_score is not None:
        lines.append(f"**Predicted Score:** {snapshot.home_team} {snapshot.predicted_home_score:.1f} - {snapshot.predicted_away_score:.1f} {snapshot.away_team}")
        lines.append("")

    if snapshot.shap_positive_drivers or snapshot.shap_negative_drivers:
        lines.append("### Key Drivers (SHAP)")
        lines.append("")
        if snapshot.shap_positive_drivers:
            lines.append("**Positive:**")
            for d in snapshot.shap_positive_drivers[:5]:
                lines.append(f"- {d.get('label', d.get('feature', ''))}")
            lines.append("")
        if snapshot.shap_negative_drivers:
            lines.append("**Negative:**")
            for d in snapshot.shap_negative_drivers[:5]:
                lines.append(f"- {d.get('label', d.get('feature', ''))}")
            lines.append("")

    if snapshot.opening_odds_home is not None:
        lines.append("### Market Dynamics")
        lines.append("")
        if snapshot.opening_odds_home:
            lines.append(f"- Opening odds (home): {snapshot.opening_odds_home:.2f}")
        if snapshot.closing_odds_home:
            lines.append(f"- Closing odds (home): {snapshot.closing_odds_home:.2f}")
        if snapshot.line_movement is not None:
            lines.append(f"- Line movement: {snapshot.line_movement:+.2f}")
        if snapshot.sharp_money_indicator:
            lines.append(f"- Sharp money: {snapshot.sharp_money_indicator}")
        if snapshot.clv is not None:
            lines.append(f"- CLV: {snapshot.clv:+.1%}")
        lines.append("")

    if snapshot.value_bets:
        lines.append("### Strategic Recommendations")
        lines.append("")
        for i, bet in enumerate(snapshot.value_bets, 1):
            selection = bet.get("selection", "Unknown")
            odds = bet.get("odds", 0)
            edge = bet.get("edge", 0)
            lines.append(f"{i}. **{selection}** @ {odds:.2f} (edge: {edge:.1%})")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by Sports Prediction System*")

    return "\n".join(lines)
