apiVersion: v1
kind: Service
metadata:
  name: reporting-service
  namespace: sports-prediction
spec:
  selector:
    app: reporting-service
  ports:
    - port: 8005
      targetPort: 8005
  type: ClusterIP
